### ISSUE TITLE
13.1-RELEASE

### ISSUE THREAD

**Issue by jasker5183** [freenas/iocage-plugin-emby#9]
I'm trying to get all the plugins updated for the 13.1-RELEASE [here](https://github.com/ix-plugin-hub/iocage-plugin-index/pull/322) and since Emby has switched from Mono to .NET the emby-server service file in your artifact repo no longer works. Any chance you could replace it with this?

[emby-server.txt](https://github.com/freenas/iocage-plugin-emby/files/9294973/emby-server.txt)

**Comment by sonicaj** [comment]
@jasker5183 can you please make a PR and we can review ? Thanks!

**Comment by jasker5183** [comment]
Filed PR three days ago. The only question I have is should the overlay folder be updated to include the new init script? Or should it be removed so the new .NET init can be installed automatically?

**Comment by sonicaj** [comment]
@jasker5183 if something can automatically be pulled in by installing a package for example, we should not be defining the same file ourselves unless we want to override of course.

Please let me know if that clarifies your question. Thanks!

**Comment by jasker5183** [comment]
Deleted the overlay directory and tested again working fine.

**Comment by Baenwort** [comment]
@sonicaj This is also fixed in: https://github.com/freenas/iocage-plugin-emby/pull/7 which is a pull request by the developers of Emby to try and address this problem that has been lingering for a while.

**Comment by jasker5183** [comment]
If that pull request was filed in July what is the hold up? I should probably close this then?

**Comment by jasker5183** [comment]
Closing this as it's a duplicate.
